"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import WorkOrder, WorkOrderCreate, WorkOrderUpdate
from .store import store

app = FastAPI(
    title="Tutorial Field service Work Orders API",
    version="0.1.0",
    description="REST API for Tutorial Field service Work Orders. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "work-orders", "description": "Work Orders managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/work-orders", response_model=List[WorkOrder], tags=["work-orders"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/work-orders", response_model=WorkOrder, status_code=201, tags=["work-orders"])
def create_item(body: WorkOrderCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/work-orders/{item_id}", response_model=WorkOrder, tags=["work-orders"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Work Order not found")
    return item


@app.patch("/api/work-orders/{item_id}", response_model=WorkOrder, tags=["work-orders"])
def update_item(item_id: int, body: WorkOrderUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Work Order not found")
    return item


@app.delete("/api/work-orders/{item_id}", status_code=204, tags=["work-orders"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Work Order not found")
